import type { Metadata } from "next";
import "@/app/globals.css";
import AdminNavBar from "@/components/AdminNavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="flex w-screen">
                    <AdminNavBar />
                    {children}
                </div>
            </body>
        </html>
    );
}
