import type { Metadata } from "next";
import "@/app/globals.css";
import NavigationBar from "@/components/NavigationBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NavigationBar />
                <div className="flex w-screen">{children}</div>
            </body>
        </html>
    );
}
