import type { Metadata } from "next";
import "@/app/globals.css";
import ShopNavBar from "@/components/ShopNavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="flex">
                    <ShopNavBar></ShopNavBar>
                    {children}
                </div>
            </body>
        </html>
    );
}
