import type { Metadata } from "next";
import "@/app/globals.css";
import NavigationBar from "@/components/NavigationBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    home,
    shops,
    categories,
}: Readonly<{
    children: React.ReactNode;
    home: React.ReactNode;
    shops: React.ReactNode;
    categories: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex flex-col items-center w-screen">
                <NavigationBar />
                {home}
                {shops}
                {categories}
            </body>
        </html>
    );
}
